# Generated by Django 6.0.3 on 2026-03-19 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', 'id'],
            },
        ),
    ]
